export const TECH_LINKS = {
  AWS: "https://aws.amazon.com/",
  "AWS EC2": "https://aws.amazon.com/ec2/",
  Anthropic: "https://www.anthropic.com/",
  "Apache Kafka": "https://kafka.apache.org/",
  "C++": "https://isocpp.org/",
  Chroma: "https://www.trychroma.com/",
  "Data Analytics": "https://www.python.org/",
  Docker: "https://www.docker.com/",
  DockerHub: "https://hub.docker.com/",
  "Express.js": "https://expressjs.com/",
  FastAPI: "https://fastapi.tiangolo.com/",
  Flask: "https://flask.palletsprojects.com/",
  Git: "https://git-scm.com/",
  Haystack: "https://haystack.deepset.ai/",
  "Hugging Face": "https://huggingface.co/",
  JavaScript: "https://www.javascript.com/",
  "Jetson Nano":
    "https://developer.nvidia.com/embedded/jetson-nano-developer-kit",
  Kafka: "https://kafka.apache.org/",
  LangChain: "https://www.langchain.com/",
  LightGBM: "https://lightgbm.readthedocs.io/",
  Linux: "https://www.kernel.org/",
  LlamaIndex: "https://www.llamaindex.ai/",
  "Machine Learning": "https://scikit-learn.org/",
  "Next.js": "https://nextjs.org/",
  "Node.js": "https://nodejs.org/",
  ONNX: "https://onnx.ai/",
  "ONNX Runtime": "https://onnxruntime.ai/",
  OpenAI: "https://openai.com/",
  OpenCV: "https://opencv.org/",
  Pinecone: "https://www.pinecone.io/",
  PostgreSQL: "https://www.postgresql.org/",
  PyTorch: "https://pytorch.org/",
  Python: "https://www.python.org/",
  Qdrant: "https://qdrant.tech/",
  RAG: "https://haystack.deepset.ai/",
  Render: "https://render.com/",
  Rust: "https://www.rust-lang.org/",
  SQL: "https://www.postgresql.org/",
  "Scikit-Learn": "https://scikit-learn.org/",
  "Tailwind CSS": "https://tailwindcss.com/",
  TensorRT: "https://developer.nvidia.com/tensorrt",
  TypeScript: "https://www.typescriptlang.org/",
  Weaviate: "https://weaviate.io/",
  XGBoost: "https://xgboost.readthedocs.io/",
} as const;
