/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

import * as React from "react";

export const Index: Record<string, any> = {
  "link-reveal": {
    name: "link-reveal",
    description:
      "Animated link that reveals the website favicon and primary color on hover.",
    type: "registry:component",
    files: [
      {
        path: "registry/components/link-reveal/types.ts",
        type: "registry:lib",
      },
      {
        path: "registry/components/link-reveal/server.ts",
        type: "registry:lib",
      },
      {
        path: "registry/components/link-reveal/link-reveal.tsx",
        type: "registry:component",
        target: "@/components/link-reveal.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/link-reveal/link-reveal");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "link-reveal";
      return { default: mod.default || mod[exportName] };
    }),
    categories: ["effects"],
    meta: null,
  },
};
